margin=92
remove_extra_newlines=true
always_for_in=true
import_to_using=true
pipe_to_function_call=false
short_to_long_function_def=false
long_to_short_function_def=false
always_use_return=false
whitespace_in_kwargs=false
format_docstrings=true
annotate_untyped_fields_with_any=true
conditional_to_if=true
normalize_line_endings="unix"
trailing_comma=true
join_lines_based_on_source=false
indent_submodule=true
separate_kwargs_with_semicolon=true
surround_whereop_typeparameters=true
for_in_replacement="in"
overwrite=false
format_markdown=true
