[workspace]
projects = [
    "Ccxt",
    "Cli", 
    "Collections",
    "Data",
    "Engine",
    "Exchanges",
    "ExchangeTypes",
    "Executors",
    "FeatureSelection",
    "Fetch",
    "Instances",
    "Instruments",
    "Lang",
    "LiveMode",
    "Metrics",
    "Misc",
    "Optim",
    "OrderTypes",
    "PaperMode",
    "Pbar",
    "Planar",
    "PlanarDev",
    "PlanarInteractive",
    "Plotting",
    "Processing",
    "Python",
    "Remote",
    "Scrapers",
    "SimMode",
    "Simulations",
    "Strategies",
    "StrategyStats",
    "StrategyTools",
    "Stubs",
    "TimeTicks",
    "Watchers",
    # Vendor packages
    "DBnomics",
    "Zarr"
]

[weakdeps]
CausalityTools = "01837fd2-c099-442f-ae89-75fa208aad36"
EffectSizes = "e248de7e-9197-5860-972e-353a2af44d75"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
