name = "ExampleMargin"
uuid = "3edf4db1-b61e-49da-8473-772d2e85bdef"
version = "0.1.0"
authors = ["zbc"]

[deps]
Planar = "646fb1a4-6797-441d-ad18-3bdbde2eb86b"
PlanarCore = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
PlanarOptim = "01937fd2-c099-442f-ae89-75fa208aad36"

[strategy]
include_file = "src/ExampleMargin.jl"
margin = "Isolated"
mode = "Paper"

[sources]
Planar = {path = "../../../Planar"}
PlanarCore = {path = "../../../PlanarCore"}
PlanarOptim = {path = "../../../PlanarOptim"}
