# This file is machine-generated - editing it directly is not advised

julia_version = "1.8.2"
manifest_format = "2.0"
project_hash = "d6ad792631d6359a23e3b3ba831fd20bf4813026"

[[deps.Long]]
path = "Long"
uuid = "4332194b-c649-4273-a126-4843709b406e"
version = "0.1.0"

[[deps.MVP]]
path = "MVP"
uuid = "979b01cd-db89-4249-a98e-f526d6a7ff63"
version = "0.1.0"

[[deps.Short]]
path = "Short"
uuid = "669a2027-c4b8-428d-ba58-693007de5487"
version = "0.1.0"
