name = "LiveMode"
uuid = "c1773ea8-8a7c-4b58-b57f-053be4f98df9"
authors = ["untoreh <francesco.giannelli@yahoo.it>"]
version = "0.1.0"

[deps]
PaperMode = "b2ae67eb-72da-414f-85db-6054cbf44090"
Watchers = "4a3f9c16-ec8e-48c6-a58d-938fc30e2b4b"
