name = "Load"
uuid = "530aee93-9b5d-4423-8dbe-9bf7490b02fc"
version = "0.1.0"
authors = ["zbc"]

[deps]
PlanarDownloadTool = "38b379f7-ca41-4278-b0dc-774ced1e32bb"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Planar = "646fb1a4-6797-441d-ad18-3bdbde2eb86b"
PlanarCore = "a475c859-e357-4be2-a5e3-43038ab4b158"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PackageCompiler = "2.2.2"

[sources]
PlanarDownloadTool = {path = "../../PlanarDownloadTool"}
Planar = {path = "../../Planar"}
PlanarCore = {path = "../../PlanarCore"}
