using Test

@testset "PlanarCore" begin
    include("Ccxt/runtests.jl")
    include("Collections/runtests.jl")
    include("collections_typing.jl")
    include("dynamic_universe.jl")
    include("dynamic_universe_harness.jl")
    include("chaos_dynamic_universe.jl")
    include("Data/runtests.jl")
    include("ExchangeTypes/runtests.jl")
    include("Exchanges/runtests.jl")
    include("Executors/runtests.jl")
    include("Fetch/runtests.jl")
    include("Instances/runtests.jl")
    include("Instruments/runtests.jl")
    include("Lang/runtests.jl")
    include("Metrics/runtests.jl")
    include("pretty.jl")
    include("OrderTypes/runtests.jl")
    include("Pbar/runtests.jl")
    include("Processing/runtests.jl")
    include("SimMode/runtests.jl")
    include("Simulations/runtests.jl")
    include("Strategies/runtests.jl")
    include("Stubs/runtests.jl")
    include("TimeTicks/runtests.jl")
    include("hedged_margin.jl")
    include("test_margin_matrix.jl")
end
