name = "SimpleStrategy"
uuid = "9faf1dd7-6398-46c6-90c9-24e0234666dd"
authors = ["zbc"]
version = "0.1.0"

[deps]
Planar = "646fb1a4-6797-441d-ad18-3bdbde2eb86b"

[strategy]
include_file = "src/SimpleStrategy.jl"
margin = "NoMargin"
mode = "Sim"
