#!/bin/bash

[ -n "$PLANAR_BITMEX_SANDBOX_APIKEY" ] || { echo "missing api keys, direnv not sourced?"; exit 1; }

IMAGE_NAME="${PLANAR_IMAGE_NAME:-localhost/planar}"

podman run --rm -it \
  --user root \
  --entrypoint=/bin/bash \
  -e PLANAR_BITMEX_SANDBOX_APIKEY=$PLANAR_BITMEX_SANDBOX_APIKEY \
  -e PLANAR_BITMEX_SANDBOX_SECRET=$PLANAR_BITMEX_SANDBOX_SECRET \
  -e PLANAR_BITMEX_SANDBOX_PASSWORD=$PLANAR_BITMEX_SANDBOX_PASSWORD \
  -e PLANAR_PHEMEX_SANDBOX_APIKEY=$PLANAR_PHEMEX_SANDBOX_APIKEY \
  -e PLANAR_PHEMEX_SANDBOX_SECRET=$PLANAR_PHEMEX_SANDBOX_SECRET \
  -e PLANAR_PHEMEX_SANDBOX_PASSWORD=$PLANAR_PHEMEX_SANDBOX_PASSWORD \
  "$IMAGE_NAME"

