name = "BBWithOpt"
uuid = "49e7d402-6e80-11ee-3ea0-03e999f86b56"
authors = ["zbc <francesco.giannelli@yahoo.it>"]
version = "0.1.0"

[deps]
OnlineTechnicalIndicators = "dc2d07fb-478f-4566-8417-81bb3e5a7af1"
Optimization = "01837fd2-c099-442f-ae89-75fa208aad36"
Planar = "646fb1a4-6797-441d-ad18-3bdbde2eb86b"

[compat]
OnlineTechnicalIndicators = "0.1.0"

[strategy]
margin = "Isolated"
mode = "Sim"
