[kucoin]
futures = false
[kucoinfutures]
futures = true
[binance]
leveraged = "from"
[bybit]
[Example]
include_file = "cfg/strategies/Example.jl"
# [sources] # Alternative method to load strategy
# Example = "cfg/strategies/Example.jl" # the name of the module
