[Example]
include_file = "strategies/Example.jl"

[BareStrat]
include_file = "strategies/BareStrat.jl"

[RandomStratIso]
include_file = "strategies/RandomStratIso.jl"

[binance]
leveraged = "from"

[bybit]

[kucoin]
futures = false

[kucoinfutures]
futures = true

[sources]
MarginStrat = "strategies/MarginStrat/Project.toml"
BBWithOpt = "strategies/BBWithOpt/Project.toml"
BollingerBands = "strategies/BollingerBands/Project.toml"
TwoIntervals = "strategies/TwoIntervals/Project.toml"
ExampleMargin = "strategies/ExampleMargin/Project.toml"
TwoParameters = "strategies/TwoParameters/Project.toml"
SimpleStrategy = "strategies/SimpleStrategy/Project.toml"
