name: build-docs

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JULIA_VERSION: 1.9
      CONDA_PKG_ENV: $HOME/.CondaPkg

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      id: julia-cache
      with:
        path: |
          $HOME/.julia
          $HOME/.CondaPkg
        key: ${{ runner.os }}-julia-${{ env.JULIA_VERSION }}-cache-${{ hashFiles('Project.toml') }}
        restore-keys: |
          ${{ runner.os }}-julia-${{ env.JULIA_VERSION }}-cache-${{ hashFiles('Project.toml') }}
          ${{ runner.os }}-julia-${{ env.JULIA_VERSION }}-
          ${{ runner.os }}-
    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1'
        include-all-prereleases: true
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
    - name: Install dependencies
      run: |
        git submodule init; git submodule update
        sudo apt-get install -y xvfb xauth
        # FIXME
        [ -e ~/.cache/PingPong.jl/data ] && rm -r ~/.cache/PingPong.jl/data
        xvfb-run julia --project=. -e 'using Pkg; Pkg.add(["Documenter", "DocStringExtensions"]); Pkg.instantiate(); Pkg.precompile(); Pkg.precompile()'
    - name: Build docs
      run: |
        # FIXME
        [ -e ~/.cache/PingPong.jl/data ] && rm -r ~/.cache/PingPong.jl/data
        export JULIA_CONDAPKG_OFFLINE=yes
        julia --project=. docs/make.jl
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: ghpages
    - name: Deploy docs
      run: |
        cd ghpages
        rm -rf ./*
        cp -r ../docs/build/* .
        git add .
        git config --local user.email "github-actions@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        git commit -m "Update documentation"
        git push origin gh-pages
