name: run-tests

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JULIA_VERSION: 1
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      id: julia-cache
      with:
        path: |
          ~/.julia
          ./.conda
        key: ${{ runner.os }}-julia-${{ env.JULIA_VERSION }}-cache-${{ hashFiles('Project.toml') }}
        restore-keys: |
          ${{ runner.os }}-julia-${{ env.JULIA_VERSION }}-cache-${{ hashFiles('PingPongDev/Manifest.toml') }}
          ${{ runner.os }}-julia-${{ env.JULIA_VERSION }}-
          ${{ runner.os }}-
    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: ${{ env.JULIA_VERSION }}
        include-all-prereleases: true
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
    - name: Install dependencies
      run: |
        git submodule init; git submodule update
        sudo apt-get install -y xauth
        julia --project=PingPongDev/ -e 'import Pkg; Pkg.resolve(); Pkg.instantiate()'
    - name: Run tests
      uses: julia-actions/julia-runtest@v1
      with:
        project: "./PingPongDev"
    - name: Process coverage
      uses: julia-actions/julia-processcoverage@v1
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Save Cache
      uses: actions/cache/save@v3
      if: always()
      with:
        path: |
          $HOME/.julia
          ./.CondaPkg
        key: ${{ runner.os }}-julia-${{ env.JULIA_VERSION }}-cache-${{ hashFiles('Project.toml') }}
