name: run-tests

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JULIA_VERSION: 1

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      id: julia-cache
      with:
        path: |
          $HOME/.julia
          ./.CondaPkg
        key: ${{ runner.os }}-julia-${{ env.JULIA_VERSION }}-cache-${{ hashFiles('Project.toml') }}
        restore-keys: |
          ${{ runner.os }}-julia-${{ env.JULIA_VERSION }}-cache-${{ hashFiles('Project.toml') }}
          ${{ runner.os }}-julia-${{ env.JULIA_VERSION }}-
          ${{ runner.os }}-
    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        julia-version: ${{ env.JULIA_VERSION }}
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
    - name: Install dependencies
      run: |
        git submodule init; git submodule update
        which xvfb-run || sudo apt-get install -y xvfb xauth
        xvfb-run julia --project=. -e 'import Pkg; Pkg.resolve(); Pkg.instantiate()'
    - name: run tests
      run: julia --project=. -e 'import Pkg; Pkg.test()'
